/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ComposicaoRouteImport } from './routes/composicao'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ApiOauthCallbackRedeRouteImport } from './routes/api/oauth/callback/$rede'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposicaoRoute = ComposicaoRouteImport.update({
  id: '/composicao',
  path: '/composicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRedeRoute = ApiOauthCallbackRedeRouteImport.update({
  id: '/api/oauth/callback/$rede',
  path: '/api/oauth/callback/$rede',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/composicao': typeof ComposicaoRoute
  '/contas': typeof ContasRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/oauth/callback/$rede': typeof ApiOauthCallbackRedeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/composicao': typeof ComposicaoRoute
  '/contas': typeof ContasRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/oauth/callback/$rede': typeof ApiOauthCallbackRedeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/composicao': typeof ComposicaoRoute
  '/contas': typeof ContasRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/oauth/callback/$rede': typeof ApiOauthCallbackRedeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/calendario'
    | '/composicao'
    | '/contas'
    | '/relatorios'
    | '/api/oauth/callback/$rede'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/calendario'
    | '/composicao'
    | '/contas'
    | '/relatorios'
    | '/api/oauth/callback/$rede'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/calendario'
    | '/composicao'
    | '/contas'
    | '/relatorios'
    | '/api/oauth/callback/$rede'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  ComposicaoRoute: typeof ComposicaoRoute
  ContasRoute: typeof ContasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ApiOauthCallbackRedeRoute: typeof ApiOauthCallbackRedeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composicao': {
      id: '/composicao'
      path: '/composicao'
      fullPath: '/composicao'
      preLoaderRoute: typeof ComposicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback/$rede': {
      id: '/api/oauth/callback/$rede'
      path: '/api/oauth/callback/$rede'
      fullPath: '/api/oauth/callback/$rede'
      preLoaderRoute: typeof ApiOauthCallbackRedeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  ComposicaoRoute: ComposicaoRoute,
  ContasRoute: ContasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ApiOauthCallbackRedeRoute: ApiOauthCallbackRedeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
